server:
    port: 8765
    context-path: /schedule-platform
# 日志设定
logging:
  level:
    com.sagacn: DEBUG
  config: classpath:logback-dev.xml
  
# 数据源设定
druid:
  url: jdbc:mysql://rm-2zew6wipk07tc4vw2.mysql.rds.aliyuncs.com:3306/schedule_new?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&cachePrepStmts=true&useServerPrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useSSL=false
  username: root
  password: Evtape123
  driver-class-name: com.mysql.jdbc.Driver
  initialSize: 50
  minIdle: 50
  maxActive: 50
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: select '1+1'
  testWhileIdle: true

user:
  token:
    expire: 360000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


